### ISSUE TITLE
Отформатировать вывод информациии

### ISSUE THREAD

**Issue by dchmir** [nopSolutions/Uniteller-plugin-for-nopcommerce#1]
![23-03-2016 10-20-53](https://cloud.githubusercontent.com/assets/16794499/13978325/2dd9150c-f0e1-11e5-815f-76c705f5ca2c.png)

**Comment by skoshelev** [comment]
Closed #1

Это стандартное форматирование данного блока, так реализован вывод всех платежных методов, работающих по этому принципу.
